### PR TITLE
Merging changes of Sprint 3 to main branch. 

### PR DESCRIPTION
**Pull request by jjose14-Jacob-Jose**
Updates changes done with Sprint 3 to main branch.

### CODE REVIEW

**Review by ksharm53 — CHANGES_REQUESTED** [review]
This is merge is having conflicts. Let me check it once.

**Review by ksharm53 — CHANGES_REQUESTED** [review]
@Vashishth to resolve conflicts for add and Edit project.

**Review by ksharm53 — APPROVED** [review]
Conflicts resolved. We can merge now.

**Review by vpatel58 — APPROVED** [review]
Conflicts in my codes are resolved

**Pull request merged**
