### PR TITLE
Us#95

### PR DESCRIPTION
**Pull request by manish-m-r**

### CODE REVIEW

**Comment by manish-m-r** [comment]
@ksharm53 Can you please review and merge to main.

**Review by ksharm53 — DISMISSED** [review]
Changes are good. Please merge with main

**Review by ksharm53 — DISMISSED** [review]
ok

**Comment by manish-m-r** [comment]
@ksharma, I have updated the frontend and backend pages. Please review and help on merge

**Review by ashikelah — APPROVED** [review]
everything looks good, you can proceed with the merge

**Comment by manish-m-r** [comment]
Thanks Ashik.

**Pull request merged**
